# -*- coding: utf-8 -*-
"""Algoritmo de Regressão Linear com Método dos Mínimos Quadrados em Colaboratory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUxDyE8JrugMJpx9CBRuQZ2BGjnfDgtW
"""

import pandas as pd
import matplotlib.pyplot as plt

dados = pd.read_csv("idade_e_altura.csv",sep=';')
dados

dados.plot(kind = 'scatter', x = 'Idade', y = 'Altura')
plt.show()

xmedia = dados['Idade'].mean()
print("Idade Média é: " + str(xmedia))
ymedia = dados['Altura'].mean()
print("Altura Média é: " + str(ymedia))

tamanho = len(dados.index)
i = 0
b_den = 0
b_num = 0
while(i < tamanho):
  b_num = b_num + (dados.iloc[i]['Idade'] - xmedia)*(dados.iloc[i]['Altura'] - ymedia)
  b_den = b_den + (dados.iloc[i]['Idade'] - xmedia)*(dados.iloc[i]['Idade'] - xmedia)
  print("Iteração " + str(i) + " ===> " + str(b_den) + " ===> " + str(b_num))
  i = i+1
b = b_num/b_den
print("Coeficiente Angular: " + str(b))

a = ymedia - b*xmedia
print("Coeficiente Linear: " + str(a))

fig, ax = plt.subplots()
ax.scatter(dados['Idade'], 
           dados['Altura'])
plt.plot(dados['Idade'], b*dados['Idade'] + a, color='red')
ax.set(xlim=(14, 19),
       ylim=(1.5,1.78))
plt.grid(True)
plt.show()